- name: Deploy Cultural Analysis service
  hosts: all
  gather_facts: yes
  vars:
    timestamp: "{{ ansible_date_time.epoch }}"
  tasks:
    - name: Deployment block
      block:
        - name: Create deployment folder
          file:
            path: ~/deploy-{{ timestamp }}
            state: directory

        - name: Clone deployment repo
          git:
            repo: 'https://github.com/romangr/cultural-footprint-deploy.git'
            dest: ~/deploy-{{ timestamp }}

        - name: Start up database
          docker_compose:
            project_src: ~/deploy-{{ timestamp }}
            project_name: cultural_footprint
            services: mongo
            state: present

        - name: Start up application
          docker_compose:
            project_src: ~/deploy-{{ timestamp }}
            project_name: cultural_footprint
            services: analysis
            state: present
            pull: yes

      always:
        - name: Remove deployment folder
          file:
            path: ~/deploy-{{ timestamp }}
            state: absent
