name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: docker login docker.pkg.github.com -u romangr -p ${{ secrets.GITHUB_TOKEN }} && docker build . --file Dockerfile --tag docker.pkg.github.com/romangr/culturalfootprintanalysis/culturalfootprintanalysis:latest
      - name: Publish the Docker image
        run: docker push docker.pkg.github.com/romangr/culturalfootprintanalysis/culturalfootprintanalysis:latest
